apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: server
    type: mvc
spec:
  containers:
    - name: app-pod
      image: keylor/apilab03:v1
      ports:
        - containerPort: 8080  